"""
kai_voice_landing / registry.py
Voice + compliance registry for the Kai voice+landing pipeline (Phil Smith Kia).

APPROVED SPEC (source of truth, do NOT deviate):
  - cloned-voice-and-dispatch-spec.md  (skills/sales/autoalert-campaign/references)
  - approved-visual-and-voice-spec.md
  - memory HARD RULE: never edge-tts / Fred / Samantha / system / browser TTS.
  - gender map (APPROVED, asset-backed):
        F (female client) -> Zaramaya (female clone)
        M (male client)   -> Ivan     (male clone)
        unknown           -> ask Ivan / no audio + BLOCK_SEND
  NOTE: IVAN OVERRIDE 2026-08-28 — opposite gender:
        F -> Ivan (male), M -> Zaramaya (female). This is now the active map.
        (Older same-gender spec in cloned-voice-and-dispatch-spec.md is superseded.)
"""

from dataclasses import dataclass
from typing import Optional

# ---------------------------------------------------------------------------
# Approved cloned-voice assets (local MP3, Ivan-supplied / campaign-approved)
# ---------------------------------------------------------------------------
# OPPOSITE-GENDER MAP (IVAN OVERRIDE 2026-08-28):
#   F (female client) -> Ivan (male clone)
#   M (male client)   -> Zaramaya (female clone)
# This overrides the older same-gender spec in cloned-voice-and-dispatch-spec.md.
APPROVED_CLONE = {
    "F": {
        "voice_id": "ivan",
        "label": "Ivan (male)",
        "file": "/Users/clawbotlocal/voice_tests/ivan_tts.mp3",
        "gender": "male",
    },
    "M": {
        "voice_id": "zaramaya",
        "label": "Zaramaya (female)",
        "file": "/Users/clawbotlocal/voice_tests/zaramaya_tts.mp3",
        "gender": "female",
    },
}

# Reference samples for the XTTS per-client clone path (when enabled)
XTTS_REFERENCE = {
    "M": {
        "voice_id": "ivan",
        "label": "Ivan (male) — XTTS clone",
        "speaker_wav": "/Users/clawbotlocal/voice_clone/ivan_ref.wav",
        "speaker_mp3": "/Users/clawbotlocal/voice_clone/ivan_voice_sample.mp3",
    },
    "F": {
        "voice_id": "zaramaya",
        "label": "Zaramaya (female) — XTTS clone",
        "speaker_wav": "/Users/clawbotlocal/Desktop/Mp3ZARAMAYA/MP3ZARAMAYA.mp3",
        "speaker_mp3": None,
    },
}

# Forbidden voice identifiers (robotic / non-approved / non-cloned)
FORBIDDEN_VOICE_PATTERNS = (
    "fred", "samantha", "edge-tts", "edge_tts",
    "neural",  # edge-tts neural voices are also forbidden for customer audio
    "aria", "guy", "jenny", "antonio", "francisca", "francisco",
    "system", "browser", "default",
)

# Required visual constants (approved-visual-and-voice-spec.md)
PHONE_COLOR = "#E5E7EB"
CTA_GREEN = "#16a34a"
FORBIDDEN_PHONE_BLUES = ("#60a5fa", "#79c0ff")
AVATAR_INITIALS = "IS"
IVAN_PHONE_DISPLAY = "(954) 860-0537"
IVAN_PHONE_TEL = "19548600537"
AI_DISCLOSURE = "This preview and audio are generated by Ivan's AI assistant and are for Ivan's review before any customer send."
AI_DISCLOSURE_PT = "Esta pré-visualização e áudio são gerados pelo assistente de IA do Ivan e são para revisão do Ivan antes de qualquer envio ao cliente."


def select_voice(gender: str) -> dict:
    """Return the approved voice descriptor for a customer gender.

    gender: 'M', 'F', or anything else -> treated as 'unknown'.
    """
    g = (gender or "").upper()
    if g in APPROVED_CLONE:
        return dict(APPROVED_CLONE[g], gender_key=g, mode="approved_clone")
    return {
        "voice_id": "neutral",
        "label": "neutral (unknown gender)",
        "file": None,
        "gender": "unknown",
        "gender_key": "unknown",
        "mode": "ask_ivan",
    }


def is_forbidden_voice(path_or_id: str) -> bool:
    s = (path_or_id or "").lower()
    return any(p in s for p in FORBIDDEN_VOICE_PATTERNS)


@dataclass
class Lead:
    slug: str
    name: str
    gender: str            # M / F / unknown
    lang: str              # pt / en
    current_vehicle: str
    equity_estimate: str   # already formatted + marked as estimate in UI
    offer: str = ""        # human description of the offer / CTA context
    phone_display: str = IVAN_PHONE_DISPLAY
    phone_tel: str = IVAN_PHONE_TEL
    cta: str = "Book My Appraisal"
    equivalent_models: Optional[list] = None
    sms_body: str = ""
    script: str = ""

    def __post_init__(self):
        if self.equivalent_models is None:
            # Real inventory search URLs on philsmithkia.com (no promised price)
            self.equivalent_models = [
                {"name": "2027 Kia Telluride",
                 "url": "https://www.philsmithkia.com/search/new-2027-kia-telluride-lighthouse-point-fl/",
                 "note": "New Telluride inventory"},
                {"name": "2026 Kia Sorento",
                 "url": "https://www.philsmithkia.com/search/new-2026-kia-sorento-lighthouse-point-fl/",
                 "note": "3-row SUV alternative"},
                {"name": "2026 Kia Sportage",
                 "url": "https://www.philsmithkia.com/search/new-2026-kia-sportage-lighthouse-point-fl/",
                 "note": "Lower-payment option"},
            ]
        if not self.sms_body:
            self.sms_body = f"Ivan, I want the free appraisal - {self.name}"
